### ISSUE TITLE
Remove 0 results Batchs 

### ISSUE THREAD

**Issue by cubissimo** [smaxwellstewart/mongo-lambda#24]
I don't know if i'm mismatching some concept about lambda architecture, but did you think is a good idea remove batches with 0 results from collections to optimize storage size?

**Comment by smaxwellstewart** [comment]
My thinking is that it should be present as then it can easily be tested to make sure the batch actually ran. Considering the how negligible the size impact is likely to be I would rather have an empty batch for completeness and to differentiate the situation of a broken batch vs an empty batch. 

Make sense?

**Comment by cubissimo** [comment]
course, it makes total sense. I'll close this issue. Ty!
